# check example_config.yaml for more details
isotope_board:
  defaults:
    debug_enabled: false
    comm_timeout: 5
  devices:
    - name: 1
      port: COM3
    - name: 2
      port: COM4

pump:
  defaults:
    rpm: 100
    current: 400
    steps_per_degree: 7.5
    steps_per_ml: 10
    reverse_direction: false
  devices:
    - name: 1
      board_name: 1
      port_id: 0
    - name: 2
      board_name: 1
      port_id: 1
    - name: 3
      board_name: 1
      port_id: 2
    - name: 4
      board_name: 1
      port_id: 3
    - name: 5
      board_name: 2
      port_id: 0
    - name: 6
      board_name: 2
      port_id: 1
    - name: 7
      board_name: 2
      port_id: 2

valve:
  defaults:
    power: 100
    normally_open: false
  devices:
    - name: 1
      board_name: 1
      port_id: 0